### ISSUE TITLE
Evaluation scripts are not running correctly.

### ISSUE THREAD

**Issue by sudodoki** [dialogue-evaluation/AGRR-2019#2]
On python 3.7.2
When I try running
```
python3 agrr_metrics.py -b dev.csv dev.csv
```
I get following error:
```
Traceback (most recent call last):
  File "agrr_metrics.py", line 122, in <module>
    print('Binary classification quality (f1-score): ' + quality['f1_score'] )
KeyError: 'f1_score'
```
This seems to be issue with inconsistent keys `'f1-score'`/`'f1_score'`

and if I do (and without any flag b/r at all)
```
python3 agrr_metrics.py -r dev.csv dev.csv
```
I get following error:
```
Traceback (most recent call last):
  File "agrr_metrics.py", line 126, in <module>
    print('Binary classification quality (f1-score): ' + quality['classification_quality'] )
TypeError: can only concatenate str (not "float") to str
```
This seems to be fixable by casting floats to str

**Comment by TatianaShavrina** [comment]
Thank you!

Fixed in https://github.com/dialogue-evaluation/AGRR-2019/commit/cc2ec1a04548202fafbb43f8114ed05d64f0f6a9
